feat(HACBS-1262): add pipeline to push image to external registry
hacbs-release/release-bundles pull request #82
Opened 2023-02-08 14:55 UTC by johnbieren

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

2023-02-09 21:05 UTC, johnbieren commented
Depends on https://github.com/hacbs-release/release-bundles/pull/83

2023-02-10 20:05 UTC, scoheb requested changes

2023-02-10 20:05 UTC, scoheb commented on catalog/pipeline/push-to-external-registry/0.1/README.md
> +| server | The Pyxis server type to use. Options are 'production' and 'stage' | No | - |
maybe rename to be `pyxisServerType`?

2023-02-10 20:13 UTC, johnbieren commented on catalog/pipeline/push-to-external-registry/0.1/README.md
> +| server | The Pyxis server type to use. Options are 'production' and 'stage' | No | - |
done

2023-02-10 20:15 UTC, scoheb approved these changes

2023-02-10 20:50 UTC, merged